"""Update Keys Api add limit column Dev

Revision ID: 1b083ff68dec
Revises: 7936c83917b5
Create Date: 2025-09-29 17:26:14.642152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b083ff68dec'
down_revision: Union[str, None] = '7936c83917b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kucoin_api_keys', sa.Column('limit_requests', sa.Integer(), default=1000))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kucoin_api_keys', 'limit_requests')
    # ### end Alembic commands ###
