"""Update Keys Api add columns Dev

Revision ID: 61f923bea103
Revises: 1b083ff68dec
Create Date: 2025-09-29 17:43:26.714952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f923bea103'
down_revision: Union[str, None] = '1b083ff68dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kucoin_api_keys', sa.Column('requests_count', sa.Integer(), nullable=False))
    op.add_column('kucoin_api_keys', sa.Column('timedelta_refresh', sa.Integer(), nullable=False))
    op.add_column('kucoin_api_keys', sa.Column('next_refresh', sa.DateTime(), nullable=False))
    op.alter_column('kucoin_api_keys', 'limit_requests',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kucoin_api_keys', 'limit_requests',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('kucoin_api_keys', 'next_refresh')
    op.drop_column('kucoin_api_keys', 'timedelta_refresh')
    op.drop_column('kucoin_api_keys', 'requests_count')
    # ### end Alembic commands ###
